# This notebook covers about creating tensors using `constant()` and `Variable()` method. 

# Introduction to Tensors

In [1]:
 # importing tensorflow
 import tensorflow as tf

In [2]:
# getting the version
tf.__version__

'2.8.2'

## Creating tensors with tf.constant()

### Create a scalar tensor

In [3]:
zero = tf.constant(20)
print(zero)

tf.Tensor(20, shape=(), dtype=int32)


In [4]:
# Dimension of the tensor
zero.ndim

0

### Create a vector tensor

In [5]:
one = tf.constant([10, 20, 25])
print(one)

tf.Tensor([10 20 25], shape=(3,), dtype=int32)


In [6]:
# Dimension of tensor
one.ndim

1

### Create a 2 dimensional tensor

In [7]:
two = tf.constant([
    [10, 20],
    [20, 30]
])
print(two)

tf.Tensor(
[[10 20]
 [20 30]], shape=(2, 2), dtype=int32)


In [8]:
two.ndim

2

### Create a 3 dimensional tensor

In [9]:
three = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 7]
     ],
     [
         [10, 20, 30],
      [40, 50, 60]
     ]
])
print(three)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  7]]

 [[10 20 30]
  [40 50 60]]], shape=(2, 2, 3), dtype=int32)


In [10]:
three.ndim

3

## Creating tensors with tf.Variable()

### Lets create the same tensors as above
### Scalar

In [11]:
v_zero = tf.Variable(20)
v_zero

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [12]:
tf.rank(v_zero)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

### Vector

In [13]:
v_one = tf.Variable([10, 20, 25])
v_one

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 25], dtype=int32)>

In [14]:
tf.rank(v_one)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### 2 Dimensional Tensor

In [15]:
v_two = tf.Variable([
    [10, 20],
    [20, 30]
])
v_two

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [20, 30]], dtype=int32)>

In [16]:
tf.rank(v_two)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### 3 Dimensional Tensor

In [17]:
v_three = tf.Variable([
    [
        [1, 2, 3],
        [4, 5, 7]
     ],
     [
         [10, 20, 30],
      [40, 50, 60]
     ]
])
v_three

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  7]],

       [[10, 20, 30],
        [40, 50, 60]]], dtype=int32)>

In [18]:
tf.rank(v_three)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## What is the difference between Variable and Constant
- We can change the values inside Variable
- We cannot change the values inside Constant

In [19]:
new_variable = tf.Variable([10, 20])
new_constant = tf.constant([10, 20])
new_variable, new_constant

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>)

In [20]:
# Change the value at index 0
new_variable[0].assign(11)
new_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11, 20], dtype=int32)>

In [21]:
new_constant[0] = 11

TypeError: ignored

In [22]:
new_constant[0].assign(11)

AttributeError: ignored

- You can see that values for Variable tensor can be changed using assign method
- Values for constant tensors cannot be changed

## Creating random Tensors

In [23]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffling the orders of tensor elements
- Why is there a need to shuffle elements
- Lets say if there are labelled images and the first 2000 images are of dog and other 2000 are of cats
- When neural network learns through such ordered data, it may happen that the neural network will adjust its weight too much according to dog images because it has not seen cat data yet.
- Therefore, its a good idea to shuffle the data.

In [24]:
shuffle_1 = tf.constant([
    [10, 20],
    [30, 40]
])
shuffle_2 = tf.constant([
    [50, 60],
    [70, 80]
])
shuffle_1, shuffle_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[50, 60],
        [70, 80]], dtype=int32)>)

In [25]:
# shuffle without seed
tf.random.shuffle(shuffle_1)
tf.random.shuffle(shuffle_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 60],
       [70, 80]], dtype=int32)>

In [26]:
# shuffle with seed
tf.random.set_seed(42) # global
tf.random.shuffle(shuffle_1, seed=42) # operational level seed
tf.random.shuffle(shuffle_2, seed=42)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 60],
       [70, 80]], dtype=int32)>

> In order to get the shuffled tensors to be same, we need to use operational level random seed and global level random seed

## Creating tensors from Numpy arrays

In [27]:
# creating tensors of all ones
tf.ones([10, 20])

<tf.Tensor: shape=(10, 20), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
     

In [28]:
# creating tensor of all zeros
tf.zeros([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

### Turn Numpy arrays into tensors 
> because tensors can be used with GPU and thus it will be much faster than numpy

In [29]:
import numpy as np
x = np.arange(1, 10, dtype=np.int32)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [30]:
# converting to tensor
tensor_X = tf.constant(x)
tensor_X

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [31]:
tensor_Y = tf.constant(x, shape=(3, 3))
tensor_Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

### Getting information from tensor
- Shape
- Rank
- Axis or dimension 
- Size

In [32]:
# Create a tensor
tensor_4 = tf.zeros([2, 3, 4, 5])
tensor_4.shape, tensor_4.ndim, tf.rank(tensor_4), tf.size(tensor_4)

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [33]:
print("Shape of the tensor: ", tensor_4.shape)
print("Dimension of the tensor: ", tensor_4.ndim)
print("Rank of the tensor as a object: ", tf.rank(tensor_4))
print("Rank of the tensor: ", tf.rank(tensor_4).numpy())
print("Size of the tensor as a object: ", tf.size(tensor_4))
print("Size of the tensor: ", tf.size(tensor_4).numpy())

Shape of the tensor:  (2, 3, 4, 5)
Dimension of the tensor:  4
Rank of the tensor as a object:  tf.Tensor(4, shape=(), dtype=int32)
Rank of the tensor:  4
Size of the tensor as a object:  tf.Tensor(120, shape=(), dtype=int32)
Size of the tensor:  120


### Indexing in Tensorflow
- It works similar to python lists

In [34]:
# Get the first 3 elements of each dimension
tensor_4[:3, :3, :3, :3]

<tf.Tensor: shape=(2, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

- Notice the shape, since first dimension has only two rows we can get two rows with three elements in other dimensions

In [35]:
tensor_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [36]:
# Get first element from every dimension except the last one
tensor_4[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
# Ge the first element from every dimension except the second last one
tensor_4[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [38]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([
    [10, 20],
    [30, 40]
])

In [39]:
# get the last item of each row / dimension of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([20, 40], dtype=int32)>

In [40]:
# Adding an extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]]], dtype=int32)>

In [41]:
# The meaning of ... is the expansion of each axis and then adding new axis at the end
rank_2_tensor[:, :, tf.newaxis]

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]]], dtype=int32)>

In [42]:
# Another way to expand dimension
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means the last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]]], dtype=int32)>

In [43]:
# expand zeroth dimension
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10, 20],
        [30, 40]]], dtype=int32)>

> we can also add extra parameter name which will specify the output tensor name

### Manipulating Tensors (Tensor operations)
**Basic Operations**
`+`, `-`, `*`, `/`

In [44]:
tensor = tf.constant([
    [10, 20],
    [30, 40]
])
# Addition
tensor + 20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 40],
       [50, 60]], dtype=int32)>

In [45]:
# good to note that the original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [46]:
# Multiplication
tensor * 20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 400],
       [600, 800]], dtype=int32)>

In [47]:
# If you want to speed up using gpu use tf functions
tf.multiply(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 400],
       [600, 800]], dtype=int32)>

In [48]:
#subtraction
tensor - 20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10,   0],
       [ 10,  20]], dtype=int32)>

In [49]:
tf.subtract(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-10,   0],
       [ 10,  20]], dtype=int32)>

In [50]:
# Division
tensor / 20

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

In [51]:
tf.divide(tensor, 20)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.5, 1. ],
       [1.5, 2. ]])>

In [52]:
# And still the tensor remains unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

**Matrix Multiplication**
- The inner dimensions must match to perform matrix multiplication
- The output will be the shape of the outer dimensions

In [53]:
# Python way
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 700, 1000],
       [1500, 2200]], dtype=int32)>

In [54]:
# Tensor way tf.linalg.matmul
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 700, 1000],
       [1500, 2200]], dtype=int32)>

In [55]:
# Create a (3, 2) tensor
X = tf.constant([
    [10, 20],
    [30, 40],
    [50, 60]
])

# Create another (3, 2) tensor
Y = tf.constant([
    [70, 80],
    [90, 100],
    [110, 120]
])
X @ Y # this will throw an error

InvalidArgumentError: ignored

In [56]:
# Convert Y to proper shape
reshaped_Y = tf.reshape(Y, shape=(2, 3))

In [57]:
X @ reshaped_Y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2700,  3000,  3300],
       [ 6100,  6800,  7500],
       [ 9500, 10600, 11700]], dtype=int32)>

In [58]:
# You can also transpose the y tensor
transposed_Y = tf.transpose(Y)

In [59]:
transposed_Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 70,  90, 110],
       [ 80, 100, 120]], dtype=int32)>

In [60]:
reshaped_Y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 70,  80,  90],
       [100, 110, 120]], dtype=int32)>

> There is difference between transpose and reshape
- transpose will flip the axis
- reshape will shuffle the elements in the desired shape specified

In [61]:
# Matmul
tf.matmul(X, transposed_Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2300,  2900,  3500],
       [ 5300,  6700,  8100],
       [ 8300, 10500, 12700]], dtype=int32)>

> **Dot Product**
- Using tf.matmul()
- Using tf.tensordot()

In [62]:
# Both ways
tf.matmul(X, transposed_Y), tf.tensordot(X, transposed_Y, axes=1)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 2300,  2900,  3500],
        [ 5300,  6700,  8100],
        [ 8300, 10500, 12700]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 2300,  2900,  3500],
        [ 5300,  6700,  8100],
        [ 8300, 10500, 12700]], dtype=int32)>)

## Changing the datatype of a tensor
- 🛠 **Resources** on **Precision** https://www.tensorflow.org/guide/mixed_precision
- The default is 32 bit precision
- To accelerate the performance, we can reduce precision to 16 bit tensors

In [63]:
tensor = tf.constant([10., 20.])
tensor.dtype

tf.float32

In [64]:
tensor_int = tf.constant([10, 20])
tensor_int.dtype

tf.int32

- If you observe both are 32 bit precision 

In [65]:
# Reduce precision to 16 bit
tensor = tf.cast(tensor, dtype=tf.float16)
tensor.dtype

tf.float16

## Aggregating tensors
- `absolute values`
- `minimum`
- `maximum`
- `mean`
- `sum`

In [66]:
# Create a random tensor between a certain range
random_tensor = tf.constant(np.random.randint(0, 100, size=50))

In [67]:
random_tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([94,  8, 66,  5, 79, 64, 31, 49, 18, 58, 58, 26, 43, 54, 17, 45, 13,
       20, 43, 64, 23, 38, 32, 56, 62, 13,  8, 16, 97, 41, 43, 48, 96, 79,
       34, 73, 83, 82, 48,  0, 85, 82, 79, 77, 11, 82, 95, 11, 77, 90])>

In [68]:
# Get the absolute value
negative_tensor = tf.constant([-7, -3])
tf.abs(negative_tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [69]:
# Get the minimum of the tensor
print("Mininum: ",tf.reduce_min(random_tensor))

# Get the maximum of the tensor
print("Maximum: ", tf.reduce_max(random_tensor))

# Get the mean of the tensor
print("Mean: ", tf.reduce_mean(random_tensor))

# Get the sum of the tensor
print("Sum: ", tf.reduce_sum(random_tensor))

Mininum:  tf.Tensor(0, shape=(), dtype=int64)
Maximum:  tf.Tensor(97, shape=(), dtype=int64)
Mean:  tf.Tensor(50, shape=(), dtype=int64)
Sum:  tf.Tensor(2516, shape=(), dtype=int64)


- For calculating standard Deviation use `reduce_std`
- For calculating variance use `reduce_variance`
- `reduce_all` - Performs logical and
- `reduce_any` - Performs logical or

In [70]:
# Standard deviation
print("Standard Deviation: ", tf.reduce_std(random_tensor)) # Cannot directly do this
print("Variance: ", tf.reduce_variance(random_tensor))

AttributeError: ignored

In [71]:
# For this to work we need to first import tensorflow_probability
import tensorflow_probability as tfp
# find the variance
tfp.stats.variance(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=828>

In [75]:
# Another way is to cast 
tf.math.reduce_variance(tf.cast(random_tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=828.05756>

In [72]:
# finding the standard deviation
tf.math.reduce_std(random_tensor)

TypeError: ignored

- We need the input as real or complex that means we need to first convert it into float or complex

In [74]:
# cast the input into float
tf.math.reduce_std(tf.cast(random_tensor, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.77599>

## Find the positional maximum and minimum

In [77]:
# Create a random tensor
tf.random.set_seed(42)
positional_tensor = tf.random.uniform(shape=[50])
positional_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [78]:
# Find the index for the positional maximum
tf.argmax(positional_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [79]:
# Finding the value at the index
positional_tensor[tf.argmax(positional_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [80]:
# Find the max with reduce_max
tf.reduce_max(positional_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [81]:
# Same way find the minimum index
tf.argmin(positional_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [82]:
# find the value of the minimum
positional_tensor[tf.argmin(positional_tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [83]:
# Another way using reduce_min
tf.reduce_min(positional_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor (Removing all single dimensions)

In [84]:
tf.random.set_seed(42)
one_tensor = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))

In [85]:
one_tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [86]:
# Now if you want to convert it into only 50 elements by removing 1 dimensions
squeezed_tensor = tf.squeeze(one_tensor)

In [87]:
squeezed_tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

> Squeeze removes all the 1 dimensions

## One Hot Encoding Tensors

In [89]:
# Create a list of indices
example_list = [0, 1, 2, 3]
# Create a one hot encoding
tf.one_hot(example_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [90]:
# Custom values with on value and off value
tf.one_hot(example_list, depth=4, on_value="T", off_value="F")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'T', b'F', b'F', b'F'],
       [b'F', b'T', b'F', b'F'],
       [b'F', b'F', b'T', b'F'],
       [b'F', b'F', b'F', b'T']], dtype=object)>

## Square, square root and log

In [91]:
new_tensor = tf.range(1, 10)
new_tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [92]:
# Squares
tf.square(new_tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [93]:
# square root
tf.sqrt(new_tensor)

InvalidArgumentError: ignored

In [94]:
tf.sqrt(tf.cast(new_tensor, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [96]:
# Log
tf.math.log(tf.cast(new_tensor, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy


In [97]:
C = tf.constant(np.array([1., 2., 3., 4.]))
C

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([1., 2., 3., 4.])>

In [99]:
# Convert tensor to numpy
numpy_C = np.array(C)

In [101]:
# Convert tensor to numpy another method
C.numpy()

array([1., 2., 3., 4.])

In [102]:
# Difference between numpy tensor and default tensor
numpy_C = tf.constant(np.array([1., 2., 3.]))
tensor_C = tf.constant([1.,2., 3.])
numpy_C, tensor_C

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>)

> As you can see, the second one is a reduced precision and is much faster

## Accessing the GPU
- Go to runtime 
- Change runtime type
- go to hardware accelerator and select GPU or TPU

In [104]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
# !nvidia-smi
# this is a tool to find how much of the GPU is used
# It runs on CUDA 