# This notebook covers about creating tensors using `constant()` and `Variable()` method. 

# Introduction to Tensors

In [1]:
 # importing tensorflow
 import tensorflow as tf

In [2]:
# getting the version
tf.__version__

'2.8.2'

## Creating tensors with tf.constant()

### Create a scalar tensor

In [3]:
zero = tf.constant(20)
print(zero)

tf.Tensor(20, shape=(), dtype=int32)


In [4]:
# Dimension of the tensor
zero.ndim

0

### Create a vector tensor

In [5]:
one = tf.constant([10, 20, 25])
print(one)

tf.Tensor([10 20 25], shape=(3,), dtype=int32)


In [6]:
# Dimension of tensor
one.ndim

1

### Create a 2 dimensional tensor

In [7]:
two = tf.constant([
    [10, 20],
    [20, 30]
])
print(two)

tf.Tensor(
[[10 20]
 [20 30]], shape=(2, 2), dtype=int32)


In [8]:
two.ndim

2

### Create a 3 dimensional tensor

In [9]:
three = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 7]
     ],
     [
         [10, 20, 30],
      [40, 50, 60]
     ]
])
print(three)

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  7]]

 [[10 20 30]
  [40 50 60]]], shape=(2, 2, 3), dtype=int32)


In [10]:
three.ndim

3

## Creating tensors with tf.Variable()

### Lets create the same tensors as above
### Scalar

In [11]:
v_zero = tf.Variable(20)
v_zero

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

In [20]:
tf.rank(v_zero)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

### Vector

In [21]:
v_one = tf.Variable([10, 20, 25])
v_one

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([10, 20, 25], dtype=int32)>

In [22]:
tf.rank(v_one)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

### 2 Dimensional Tensor

In [23]:
v_two = tf.Variable([
    [10, 20],
    [20, 30]
])
v_two

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10, 20],
       [20, 30]], dtype=int32)>

In [24]:
tf.rank(v_two)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

### 3 Dimensional Tensor

In [25]:
v_three = tf.Variable([
    [
        [1, 2, 3],
        [4, 5, 7]
     ],
     [
         [10, 20, 30],
      [40, 50, 60]
     ]
])
v_three

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  7]],

       [[10, 20, 30],
        [40, 50, 60]]], dtype=int32)>

In [26]:
tf.rank(v_three)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

## What is the difference between Variable and Constant
- We can change the values inside Variable
- We cannot change the values inside Constant

In [27]:
new_variable = tf.Variable([10, 20])
new_constant = tf.constant([10, 20])
new_variable, new_constant

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 20], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 20], dtype=int32)>)

In [29]:
# Change the value at index 0
new_variable[0].assign(11)
new_variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([11, 20], dtype=int32)>

In [30]:
new_constant[0] = 11

TypeError: ignored

In [31]:
new_constant[0].assign(11)

AttributeError: ignored

- You can see that values for Variable tensor can be changed using assign method
- Values for constant tensors cannot be changed